# Generated by Django 4.2.1 on 2023-11-07 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0002_remove_acperson_ac'),
    ]

    operations = [
        migrations.AddField(
            model_name='acperson',
            name='ac',
            field=models.ForeignKey(blank=True, db_column='AC_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.agingclock'),
        ),
        migrations.AddField(
            model_name='geneinteraction',
            name='gene1',
            field=models.ForeignKey(blank=True, db_column='gene1_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.gene'),
        ),
        migrations.AddField(
            model_name='geneinteraction',
            name='gene2',
            field=models.ForeignKey(blank=True, db_column='gene2_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geneinteraction_gene2_set', to='longevity.gene'),
        ),
    ]
