# Generated by Django 4.2.1 on 2023-11-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0003_acperson_ac_geneinteraction_gene1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gene',
            options={'ordering': ['gsymbol']},
        ),
    ]
