# Generated by Django 4.2.1 on 2023-11-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0004_alter_gene_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='protein',
            field=models.CharField(blank=True, db_column='protein', max_length=40, null=True),
        ),
    ]
