# Generated by Django 4.2.1 on 2023-11-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0005_gene_protein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='protein',
            field=models.CharField(blank=True, db_column='protein', max_length=60, null=True),
        ),
    ]
