# Generated by Django 4.2.1 on 2023-11-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0006_alter_gene_protein'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genespecies',
            options={'ordering': ['gene__gsymbol']},
        ),
    ]
