# Generated by Django 4.2.1 on 2023-11-07 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0007_alter_genespecies_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gsgene',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='gsgene',
            name='gs',
        ),
        migrations.RemoveField(
            model_name='nodediagnosis',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='nodediagnosis',
            name='node',
        ),
        migrations.RemoveField(
            model_name='nodegs',
            name='gs',
        ),
        migrations.RemoveField(
            model_name='nodegs',
            name='node',
        ),
        migrations.RemoveField(
            model_name='project',
            name='keyobjectives',
        ),
        migrations.RemoveField(
            model_name='project',
            name='overallgoal',
        ),
        migrations.AlterField(
            model_name='diagnosedt',
            name='diagnosis',
            field=models.ForeignKey(db_column='Diagnosis_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.diagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_id',
            field=models.AutoField(db_column='Diagnosis_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnosisbm',
            name='diagnosis',
            field=models.ForeignKey(blank=True, db_column='Diagnosis_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.diagnosis'),
        ),
        migrations.AlterField(
            model_name='projectdiagnosis',
            name='diagnosis',
            field=models.ForeignKey(blank=True, db_column='Diagnosis_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.diagnosis'),
        ),
        migrations.DeleteModel(
            name='geneinteraction',
        ),
        migrations.DeleteModel(
            name='GeneSet',
        ),
        migrations.DeleteModel(
            name='gsgene',
        ),
        migrations.DeleteModel(
            name='InteractionType',
        ),
        migrations.DeleteModel(
            name='NodeDiagnosis',
        ),
        migrations.DeleteModel(
            name='nodegs',
        ),
    ]
