# Generated by Django 4.2.1 on 2023-11-07 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0008_remove_gsgene_gene_remove_gsgene_gs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneSet',
            fields=[
                ('gs_id', models.AutoField(primary_key=True, serialize=False)),
                ('gstitle', models.CharField(blank=True, db_column='gstitle', max_length=50, null=True)),
                ('gsdesc', models.TextField(blank=True, db_column='gsdesc', null=True)),
            ],
            options={
                'db_table': 'geneset',
            },
        ),
        migrations.CreateModel(
            name='InteractionType',
            fields=[
                ('it_id', models.AutoField(primary_key=True, serialize=False)),
                ('interaction', models.CharField(blank=True, db_column='interaction', max_length=30, null=True)),
                ('typedesc', models.TextField(blank=True, db_column='typedesc', null=True)),
            ],
            options={
                'db_table': 'interactiontype',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='keyobjectives',
            field=models.TextField(blank=True, db_column='keyobjectives', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='overallgoal',
            field=models.TextField(blank=True, db_column='overallgoal', null=True),
        ),
        migrations.AlterField(
            model_name='diagnosedt',
            name='diagnosis',
            field=models.ForeignKey(db_column='diagnosis_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.diagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_id',
            field=models.AutoField(db_column='diagnosis_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnosisbm',
            name='diagnosis',
            field=models.ForeignKey(blank=True, db_column='diagnosis_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.diagnosis'),
        ),
        migrations.AlterField(
            model_name='projectdiagnosis',
            name='diagnosis',
            field=models.ForeignKey(blank=True, db_column='diagnosis_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.diagnosis'),
        ),
        migrations.CreateModel(
            name='nodegs',
            fields=[
                ('ngs_id', models.AutoField(primary_key=True, serialize=False)),
                ('gs', models.ForeignKey(db_column='gs_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.geneset')),
                ('node', models.ForeignKey(db_column='Node_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.node')),
            ],
            options={
                'db_table': 'nodegs',
            },
        ),
        migrations.CreateModel(
            name='NodeDiagnosis',
            fields=[
                ('nd_id', models.AutoField(primary_key=True, serialize=False)),
                ('nddesc', models.TextField(blank=True, db_column='nddesc', null=True)),
                ('diagnosis', models.ForeignKey(db_column='diagnosis_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.diagnosis')),
                ('node', models.ForeignKey(db_column='Node_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.node')),
            ],
            options={
                'db_table': 'nodediagnosis',
            },
        ),
        migrations.CreateModel(
            name='gsgene',
            fields=[
                ('gsg_id', models.AutoField(primary_key=True, serialize=False)),
                ('generole', models.IntegerField(blank=True, db_column='generole', null=True)),
                ('gene', models.ForeignKey(db_column='gene_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.gene')),
                ('gs', models.ForeignKey(db_column='gs_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.geneset')),
            ],
            options={
                'db_table': 'gsgene',
            },
        ),
        migrations.CreateModel(
            name='geneinteraction',
            fields=[
                ('gi_id', models.AutoField(primary_key=True, serialize=False)),
                ('gene1', models.ForeignKey(blank=True, db_column='gene1_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.gene')),
                ('gene2', models.ForeignKey(blank=True, db_column='gene2_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geneinteraction_gene2_set', to='longevity.gene')),
                ('it', models.ForeignKey(db_column='it_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.interactiontype')),
            ],
            options={
                'db_table': 'geneinteraction',
            },
        ),
    ]
