# Generated by Django 4.2.1 on 2023-11-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0009_geneset_interactiontype_project_keyobjectives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsgene',
            name='generole',
            field=models.TextField(blank=True, db_column='generole', null=True),
        ),
    ]
