# Generated by Django 4.2.1 on 2023-11-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0013_remove_node_hallmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='concept',
            fields=[
                ('conc_id', models.AutoField(primary_key=True, serialize=False)),
                ('ctitle', models.TextField(blank=True, db_column='ctitle', null=True)),
                ('cdesc', models.TextField(blank=True, db_column='cdesc', null=True)),
                ('p_conc', models.ForeignKey(blank=True, db_column='p_conc_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.concept')),
            ],
            options={
                'db_table': 'concept',
            },
        ),
        migrations.CreateModel(
            name='openproblem',
            fields=[
                ('op_id', models.AutoField(primary_key=True, serialize=False)),
                ('optitle', models.TextField(blank=True, db_column='optitle', null=True)),
                ('opdesc', models.TextField(blank=True, db_column='opdesc', null=True)),
            ],
            options={
                'db_table': 'openproblem',
            },
        ),
        migrations.CreateModel(
            name='relation',
            fields=[
                ('rela_id', models.AutoField(primary_key=True, serialize=False)),
                ('rtitle', models.TextField(blank=True, db_column='rtitle', null=True)),
                ('rdesc', models.TextField(blank=True, db_column='rdesc', null=True)),
            ],
            options={
                'db_table': 'relation',
            },
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='step',
        ),
        migrations.CreateModel(
            name='opop',
            fields=[
                ('opop_id', models.AutoField(primary_key=True, serialize=False)),
                ('op1', models.ForeignKey(db_column='op1_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.openproblem')),
                ('op2', models.ForeignKey(db_column='op2_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='opop_op2_id_set', to='longevity.openproblem')),
                ('rela', models.ForeignKey(blank=True, db_column='rela_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.relation')),
            ],
            options={
                'db_table': 'opop',
            },
        ),
        migrations.CreateModel(
            name='opintervention',
            fields=[
                ('opi_id', models.AutoField(primary_key=True, serialize=False)),
                ('intervention', models.ForeignKey(db_column='Intervention_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.intervention')),
                ('op', models.ForeignKey(db_column='op_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.openproblem')),
            ],
            options={
                'db_table': 'opintervention',
            },
        ),
        migrations.CreateModel(
            name='openconc',
            fields=[
                ('oc_id', models.AutoField(primary_key=True, serialize=False)),
                ('conc', models.ForeignKey(db_column='conc_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.concept')),
                ('op', models.ForeignKey(db_column='op_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.openproblem')),
            ],
            options={
                'db_table': 'open_conc',
            },
        ),
        migrations.CreateModel(
            name='opdiagnosis',
            fields=[
                ('opd_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis', models.ForeignKey(db_column='diagnosis_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.diagnosis')),
                ('op', models.ForeignKey(db_column='op_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.openproblem')),
            ],
            options={
                'db_table': 'opdiagnosis',
            },
        ),
        migrations.CreateModel(
            name='interventionstep',
            fields=[
                ('is_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.IntegerField(blank=True, db_column='condition', null=True)),
                ('conddesc', models.TextField(blank=True, db_column='conddesc', null=True)),
                ('intervention', models.ForeignKey(db_column='Intervention_id', on_delete=django.db.models.deletion.CASCADE, to='longevity.intervention')),
                ('step', models.ForeignKey(db_column='Step_id', on_delete=django.db.models.deletion.CASCADE, to='longevity.ddstep')),
            ],
            options={
                'db_table': 'interventionstep',
            },
        ),
    ]
