# Generated by Django 4.2.1 on 2023-11-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0015_alter_concept_ctitle'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='concept',
            table=None,
        ),
    ]
