# Generated by Django 4.2.1 on 2023-11-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0016_alter_concept_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'ordering': ['conc_id']},
        ),
        migrations.AlterModelTable(
            name='concept',
            table='concept',
        ),
    ]
