# Generated by Django 4.2.1 on 2023-11-29 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0017_alter_concept_options_alter_concept_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genage',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='gene',
        ),
        migrations.AlterField(
            model_name='genespecies',
            name='gene',
            field=models.ForeignKey(blank=True, db_column='gene_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.gene'),
        ),
        migrations.AlterField(
            model_name='gsgene',
            name='gene',
            field=models.ForeignKey(blank=True, db_column='gene_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.gene'),
        ),
        # migrations.AlterField(
            # model_name='interventiongene',
            # name='gene',
            # field=models.ForeignKey(blank=True, db_column='gene_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.gene'),
        # ),
        migrations.DeleteModel(
            name='Cellage',
        ),
        migrations.DeleteModel(
            name='Genage',
        ),
        migrations.DeleteModel(
            name='Signature',
        ),
    ]
