# Generated by Django 4.2.1 on 2023-11-29 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0019_signature_genage_cellage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionGene',
            fields=[
                ('ig_id', models.AutoField(primary_key=True, serialize=False)),
                ('gene', models.ForeignKey(blank=True, db_column='gene_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.gene')),
                ('intervention', models.ForeignKey(db_column='Intervention_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.intervention')),
            ],
            options={
                'db_table': 'intervention_gene',
            },
        ),
    ]
