# Generated by Django 4.2.1 on 2023-12-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0020_interventiongene'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node0',
            fields=[
                ('node_id', models.IntegerField(db_column='Node_id', primary_key=True, serialize=False)),
                ('ref_num', models.CharField(blank=True, db_column='Ref_num', max_length=3, null=True)),
                ('nodecaption', models.CharField(blank=True, db_column='NodeCaption', max_length=254, null=True)),
            ],
            options={
                'db_table': 'node0',
                'ordering': ['ref_num'],
            },
        ),
        migrations.CreateModel(
            name='Edge0',
            fields=[
                ('edge_id', models.AutoField(db_column='Edge_id', primary_key=True, serialize=False)),
                ('begin', models.ForeignKey(db_column='Begin_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.node0')),
                ('end', models.ForeignKey(db_column='End_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='edge_end_set', to='longevity.node0')),
            ],
            options={
                'db_table': 'edge0',
            },
        ),
    ]
