# Generated by Django 4.2.1 on 2023-12-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0021_node0_edge0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node0',
            name='node_id',
            field=models.AutoField(db_column='Node_id', primary_key=True, serialize=False),
        ),
    ]
