# Generated by Django 4.2.1 on 2023-12-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0022_alter_node0_node_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edge0',
        ),
        migrations.DeleteModel(
            name='Node0',
        ),
    ]
