# Generated by Django 4.2.1 on 2024-01-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0023_delete_edge0_delete_node0'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='parent_n',
            field=models.ForeignKey(blank=True, db_column='Parent_n_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='longevity.node'),
        ),
    ]
