# Generated by Django 4.2.1 on 2024-01-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0024_node_parent_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='height',
            field=models.IntegerField(blank=True, db_column='height', null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='width',
            field=models.IntegerField(blank=True, db_column='width', null=True),
        ),
    ]
