# Generated by Django 4.2.1 on 2024-01-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0025_node_height_node_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='posx',
            field=models.IntegerField(blank=True, db_column='posx', null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='posy',
            field=models.IntegerField(blank=True, db_column='posy', null=True),
        ),
    ]
