# Generated by Django 4.2.1 on 2024-02-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0026_node_posx_node_posy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='adsens',
        ),
        migrations.RemoveField(
            model_name='node',
            name='adspec',
        ),
        migrations.AddField(
            model_name='node',
            name='cyrend',
            field=models.IntegerField(blank=True, db_column='cyrend', null=True),
        ),
    ]
