# Generated by Django 4.2.1 on 2024-02-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0027_remove_node_adsens_remove_node_adspec_node_cyrend'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='adsens',
            field=models.DecimalField(blank=True, db_column='adsens', decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='adspec',
            field=models.DecimalField(blank=True, db_column='adspec', decimal_places=2, max_digits=6, null=True),
        ),
    ]
