# Generated by Django 4.2.1 on 2024-02-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0029_node_posnx_node_posny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='posnx',
            field=models.DecimalField(blank=True, db_column='posnx', decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='posny',
            field=models.DecimalField(blank=True, db_column='posny', decimal_places=4, max_digits=9, null=True),
        ),
    ]
