# Generated by Django 4.2.1 on 2024-03-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0030_alter_node_posnx_alter_node_posny'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgtype',
            name='typedesc',
            field=models.TextField(blank=True, db_column='typedesc', null=True),
        ),
        migrations.AlterField(
            model_name='orgorg',
            name='orgrelation',
            field=models.CharField(blank=True, db_column='OrgRelation', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgtype',
            name='typetitle',
            field=models.CharField(blank=True, db_column='TypeTitle', max_length=70, null=True),
        ),
        migrations.CreateModel(
            name='otot',
            fields=[
                ('otot_id', models.AutoField(db_column='otot_id', primary_key=True, serialize=False)),
                ('orgtyperelation', models.CharField(blank=True, db_column='orgtyperelation', max_length=50, null=True)),
                ('cot_id', models.ForeignKey(db_column='cot_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='otot_ot_id_set', to='longevity.orgtype')),
                ('pot_id', models.ForeignKey(db_column='pot_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.orgtype')),
            ],
            options={
                'db_table': 'otot',
            },
        ),
    ]
