# Generated by Django 4.2.1 on 2024-06-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0032_benefit_benefittype_celltype_collaboration_collaborg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='dash',
        ),
        migrations.AlterField(
            model_name='node',
            name='container',
            field=models.IntegerField(blank=True, choices=[(1, 'Tissue, Organ, & Whole Body Physiology & Pathology'), (2, 'Whole Cells or Tissues'), (3, 'Extracellular Spaces: ECM, Blood Plasma, Lymph, CSF'), (4, 'Cytosolic Compartment of the Cell'), (5, 'Lysosome – Hydrolysis - for recycling. Accumulation in nonmitotic cells'), (6, 'Macroautophagy'), (7, 'Mitochondria in nonmitotic cell'), (8, 'Cell Nucleus – Genetics'), (9, 'Endoplasmic Reticulum'), (10, 'Cell Membrane'), (11, 'Secretion'), (12, 'Environmental Factors'), (13, 'Endoplasmic Reticulum Membrane'), (14, 'Nucleus Membrane'), (15, 'Mitochondria Membrane'), (16, 'Lysosome Membrane'), (17, 'Intervention')], db_column='Container', null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodecolor',
            field=models.IntegerField(blank=True, choices=[(1, 'Blue: Genetics, Nucleus, Endoplasmic Reticulum'), (2, 'Light Brown (Dark Yellow): Cytoplasmic molecules'), (3, 'Light Blue (Cyan): Mitochondria'), (4, 'Brown: Extracellular Substances & Structures'), (5, 'Pink (Magenta): Controlled Degradation & Turnover'), (6, 'Green: Beneficial process or intervention'), (7, 'Purple (Violet): Signaling Pathway'), (8, 'Red: Damaging Substance or Process'), (9, 'Black: Senescence Physiology'), (10, 'Orange'), (11, 'Yellow')], db_column='NodeColor', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectsource',
            field=models.IntegerField(blank=True, choices=[(1, 'The challenges currently underway to find interventions'), (2, 'Initiated'), (3, 'Running'), (4, 'Hold'), (5, 'Canceled'), (6, 'Finished')], db_column='ProjectSource', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='projstatus',
            field=models.IntegerField(blank=True, choices=[(1, 'Required'), (2, 'Projects defined  to help intervention discovery and development processes leap one step forward'), (3, 'Help the holistic approach')], db_column='ProjStatus', null=True),
        ),
        migrations.AlterField(
            model_name='sae',
            name='sae',
            field=models.IntegerField(blank=True, choices=[(1, 'Results in Death'), (2, 'Is life-threatening'), (3, 'Requires Inpatient Hospitalization or Prolongation of Existing Hospitalization'), (4, 'Results in Persistent or Significant Disability/Incapacity'), (5, 'Impacts Mental Health'), (6, 'Causes Congenital Anomaly/Birth Defect'), (7, 'Requires Medical Intervention but Not Hospitalization'), (8, 'Causes Temporary and Annoying Effects')], db_column='SAE', db_comment='Serious Adverse Event', null=True),
        ),
    ]
