# Generated by Django 4.2.1 on 2024-06-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0033_remove_node_dash_alter_node_container_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='beginrefnum',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='edge',
            name='endrefnum',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
