# Generated by Django 4.2.1 on 2024-06-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0034_edge_beginrefnum_edge_endrefnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.AutoField(db_column='Node_id', primary_key=True, serialize=False),
        ),
    ]
