# Generated by Django 4.2.1 on 2024-08-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0035_alter_node_node_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='nplit',
            fields=[
                ('npl_id', models.AutoField(primary_key=True, serialize=False)),
                ('lit', models.ForeignKey(db_column='lit_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.literature')),
                ('np', models.ForeignKey(db_column='np_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.nanoparticle')),
            ],
            options={
                'db_table': 'nplit',
            },
        ),
        migrations.DeleteModel(
            name='npintlit',
        ),
    ]
