# Generated by Django 4.2.1 on 2024-11-27 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0038_drawbackproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='icd11',
            fields=[
                ('icd11_id', models.AutoField(db_column='icd11_id', primary_key=True, serialize=False)),
                ('icd11code', models.CharField(blank=True, db_column='icd11code', max_length=20, null=True)),
                ('icd11title', models.CharField(blank=True, db_column='icd11title', max_length=254, null=True)),
            ],
            options={
                'db_table': 'icd11',
            },
        ),
        migrations.RenameModel(
            old_name='nodenodetissue',
            new_name='nodetissue',
        ),
        migrations.RemoveField(
            model_name='node',
            name='frequency_q',
        ),
        migrations.RemoveField(
            model_name='node',
            name='icd11',
        ),
        migrations.RemoveField(
            model_name='node',
            name='severity_q',
        ),
        migrations.RemoveField(
            model_name='node',
            name='speed_q',
        ),
        migrations.AddField(
            model_name='edge',
            name='edgefunction',
            field=models.CharField(blank=True, db_column='edgefunction', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='agingfunction',
            field=models.TextField(blank=True, db_column='agingfunction', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='ventropy',
            field=models.DecimalField(blank=True, db_column='ventropy', decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='vfrequency',
            field=models.DecimalField(blank=True, db_column='vfrequency', decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='vimpact',
            field=models.DecimalField(blank=True, db_column='vimpact', decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='vmortality',
            field=models.DecimalField(blank=True, db_column='vmortality', decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='vspeed',
            field=models.DecimalField(blank=True, db_column='vspeed', decimal_places=0, max_digits=3, null=True),
        ),
        migrations.CreateModel(
            name='normweight',
            fields=[
                ('nw_id', models.AutoField(db_column='nw_id', primary_key=True, serialize=False)),
                ('purpose', models.IntegerField(blank=True, choices=[(1, 'Academic Research Environment'), (2, 'Business Environment'), (3, 'Healthcare Environment')], db_column='purpose', null=True)),
                ('wmortality', models.DecimalField(blank=True, db_column='wmortality', decimal_places=0, max_digits=3, null=True)),
                ('wspeed', models.DecimalField(blank=True, db_column='wspeed', decimal_places=0, max_digits=3, null=True)),
                ('wfrequency', models.DecimalField(blank=True, db_column='wfrequency', decimal_places=0, max_digits=3, null=True)),
                ('wimpact', models.DecimalField(blank=True, db_column='wimpact', decimal_places=0, max_digits=3, null=True)),
                ('wentropy', models.DecimalField(blank=True, db_column='wentropy', decimal_places=0, max_digits=3, null=True)),
                ('node', models.ForeignKey(db_column='Node_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.node')),
            ],
            options={
                'db_table': 'normweight',
                'ordering': ['node'],
            },
        ),
        migrations.CreateModel(
            name='nodeicd11',
            fields=[
                ('ni_id', models.AutoField(db_column='ni_id', primary_key=True, serialize=False)),
                ('icd11', models.ForeignKey(blank=True, db_column='icd11_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='longevity.icd11')),
                ('node', models.ForeignKey(blank=True, db_column='node_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='longevity.node')),
            ],
            options={
                'db_table': 'nodeicd11',
            },
        ),
    ]
