# Generated by Django 4.2.1 on 2024-11-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0039_icd11_rename_nodenodetissue_nodetissue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='cystyle',
            field=models.CharField(blank=True, db_column='cystyle', max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='cystyle',
            field=models.CharField(blank=True, db_column='cystyle', max_length=450, null=True),
        ),
    ]
