# Generated by Django 4.2.1 on 2024-11-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0040_edge_cystyle_node_cystyle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='cystyle',
        ),
    ]
