# Generated by Django 4.2.1 on 2024-11-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0041_remove_edge_cystyle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='cystyle',
        ),
    ]
