# Generated by Django 4.2.1 on 2024-12-08 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0042_remove_node_cystyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='parent_n',
            field=models.ForeignKey(blank=True, db_column='Parent_n_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='longevity.node'),
        ),
    ]
