# Generated by Django 4.2.1 on 2025-03-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0043_alter_node_parent_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='toxicitymeasure',
            fields=[
                ('tm_id', models.AutoField(db_column='tm_id', primary_key=True, serialize=False)),
                ('tmtype', models.IntegerField(blank=True, choices=[(1, 'NOAEL'), (2, 'MTD'), (3, 'NTEL')], db_column='tmtype', null=True)),
                ('tixicity', models.FloatField(blank=True, db_column='toxicity', null=True)),
                ('unit', models.ForeignKey(blank=True, db_column='unit_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.toxicitymeasure')),
            ],
            options={
                'db_table': 'toxicitymeasure',
            },
        ),
        migrations.RemoveField(
            model_name='extfactnpint',
            name='npi',
        ),
        migrations.RemoveField(
            model_name='interventionsae',
            name='doselimit',
        ),
        migrations.RemoveField(
            model_name='interventionsae',
            name='unit',
        ),
        migrations.AddField(
            model_name='extfactnpint',
            name='np',
            field=models.ForeignKey(blank=True, db_column='np_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.nanoparticle'),
        ),
        migrations.AddField(
            model_name='project',
            name='plevel',
            field=models.IntegerField(blank=True, choices=[(1, 'Portfolio'), (2, 'Program'), (3, 'Project')], db_column='plevel', null=True),
        ),
        migrations.AlterField(
            model_name='extfactnpint',
            name='ef',
            field=models.ForeignKey(blank=True, db_column='ef_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.externalfactor'),
        ),
        migrations.AlterField(
            model_name='npcomponent',
            name='comp',
            field=models.ForeignKey(blank=True, db_column='comp_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.component'),
        ),
        migrations.AlterField(
            model_name='npcomponent',
            name='np',
            field=models.ForeignKey(blank=True, db_column='np_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.nanoparticle'),
        ),
        migrations.AlterField(
            model_name='npcomponent',
            name='unit',
            field=models.ForeignKey(blank=True, db_column='unit_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.unit'),
        ),
        migrations.AlterField(
            model_name='nplit',
            name='lit',
            field=models.ForeignKey(blank=True, db_column='lit_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.literature'),
        ),
        migrations.AlterField(
            model_name='nplit',
            name='np',
            field=models.ForeignKey(blank=True, db_column='np_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.nanoparticle'),
        ),
        migrations.AlterField(
            model_name='pronp',
            name='np',
            field=models.ForeignKey(blank=True, db_column='NP_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.nanoparticle'),
        ),
        migrations.AlterField(
            model_name='pronp',
            name='prot',
            field=models.ForeignKey(blank=True, db_column='Prot_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.protocol'),
        ),
        migrations.DeleteModel(
            name='DoseUnit',
        ),
        migrations.AddField(
            model_name='interventionsae',
            name='tm',
            field=models.ForeignKey(blank=True, db_column='tm_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.toxicitymeasure'),
        ),
        migrations.AddField(
            model_name='nanoparticle',
            name='tm',
            field=models.ForeignKey(blank=True, db_column='tm_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.toxicitymeasure'),
        ),
    ]
