# Generated by Django 4.2.1 on 2025-07-28 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0044_toxicitymeasure_remove_extfactnpint_npi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='certification',
            fields=[
                ('cert_id', models.AutoField(primary_key=True, serialize=False)),
                ('certtype', models.IntegerField(blank=True, db_column='certtype', null=True)),
                ('certtitle', models.CharField(blank=True, db_column='certtitle', max_length=30, null=True)),
                ('certdesc', models.TextField(blank=True, db_column='certdesc', null=True)),
            ],
            options={
                'db_table': 'certification',
            },
        ),
        migrations.CreateModel(
            name='certorg',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, db_column='score', null=True)),
                ('link', models.CharField(blank=True, db_column='link', max_length=255, null=True)),
                ('cert', models.ForeignKey(blank=True, db_column='cert_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.certification')),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.organization')),
            ],
            options={
                'db_table': 'certorg',
            },
        ),
        migrations.CreateModel(
            name='certpl',
            fields=[
                ('cpl_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, db_column='score', null=True)),
                ('link', models.CharField(blank=True, db_column='link', max_length=255, null=True)),
                ('cert', models.ForeignKey(blank=True, db_column='cert_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.certification')),
            ],
            options={
                'db_table': 'certpl',
            },
        ),
        migrations.CreateModel(
            name='certso',
            fields=[
                ('cso_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, db_column='score', null=True)),
                ('link', models.CharField(blank=True, db_column='link', max_length=255, null=True)),
                ('cert', models.ForeignKey(blank=True, db_column='cert_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.certification')),
            ],
            options={
                'db_table': 'certso',
            },
        ),
        migrations.CreateModel(
            name='comprecep',
            fields=[
                ('cr_id', models.AutoField(db_column='cr_id', primary_key=True, serialize=False)),
                ('comp', models.ForeignKey(blank=True, db_column='comp_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.component')),
            ],
            options={
                'db_table': 'comprecep',
            },
        ),
        migrations.CreateModel(
            name='intcelltype',
            fields=[
                ('ict_id', models.AutoField(db_column='ict_id', primary_key=True, serialize=False)),
                ('ct', models.ForeignKey(blank=True, db_column='ct_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='longevity.celltype')),
                ('intervention', models.ForeignKey(blank=True, db_column='intervention_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='longevity.intervention')),
            ],
            options={
                'db_table': 'intcelltype',
            },
        ),
        migrations.CreateModel(
            name='inttissue',
            fields=[
                ('it_id', models.AutoField(db_column='it_id', primary_key=True, serialize=False)),
                ('intervention', models.ForeignKey(blank=True, db_column='intervention_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='longevity.intervention')),
                ('tissue', models.ForeignKey(blank=True, db_column='tissue_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='longevity.tissue')),
            ],
            options={
                'db_table': 'inttissue',
            },
        ),
        migrations.CreateModel(
            name='nptype',
            fields=[
                ('npt_id', models.AutoField(db_column='npt_id', primary_key=True, serialize=False)),
                ('npttitle', models.CharField(blank=True, db_column='npttitle', max_length=30, null=True)),
                ('nptdesc', models.TextField(blank=True, db_column='nptdesc', null=True)),
                ('pnpt', models.ForeignKey(blank=True, db_column='pnpt_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.nptype')),
            ],
            options={
                'db_table': 'nptype',
            },
        ),
        migrations.CreateModel(
            name='proteinreceptor',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('protein', models.ForeignKey(db_column='protein_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.protein')),
            ],
            options={
                'db_table': 'proteinreceptor',
            },
        ),
        migrations.CreateModel(
            name='receptor',
            fields=[
                ('receptor_id', models.AutoField(db_column='receptor_id', primary_key=True, serialize=False)),
                ('receptorname', models.CharField(blank=True, db_column='receptorname', max_length=50, null=True)),
                ('receptordesc', models.TextField(blank=True, db_column='receptordesc', null=True)),
            ],
            options={
                'db_table': 'receptor',
            },
        ),
        migrations.CreateModel(
            name='servorg',
            fields=[
                ('so_id', models.AutoField(db_column='so_id', primary_key=True, serialize=False)),
                ('tat', models.DecimalField(blank=True, db_column='tat', decimal_places=0, max_digits=4, null=True)),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.organization')),
                ('serv_id', models.ForeignKey(db_column='serv_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.service')),
            ],
            options={
                'db_table': 'servorg',
            },
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='supl',
        ),
        migrations.RemoveField(
            model_name='toxicitymeasure',
            name='tixicity',
        ),
        migrations.AddField(
            model_name='nanoparticle',
            name='profiletype',
            field=models.IntegerField(blank=True, choices=[(1, 'Reference'), (2, 'Studied'), (3, 'Research Goal')], db_column='profiletype', null=True),
        ),
        migrations.AddField(
            model_name='toxicitymeasure',
            name='toxicityvalue',
            field=models.FloatField(blank=True, db_column='toxicityvalue', null=True),
        ),
        migrations.AlterField(
            model_name='toxicitymeasure',
            name='tmtype',
            field=models.IntegerField(blank=True, choices=[(1, 'NOAEL (no Observed Adverse Effect Level)'), (2, 'NOEL (No Observed Effect Level)'), (3, 'MTD (maximum tolerated dose)'), (4, 'NTEL (no toxic effect level)'), (5, 'LD50 (Lethal Dose, 50%)'), (6, 'IC50 (inhibitory concentration 50%)'), (7, 'EC50 (Effective Concentration 50%)'), (8, 'ED50 (Effective Dose 50%)'), (9, 'TD50 (Toxic Dose 50%)'), (10, 'LOAEL (Lowest Observed Adverse Effect Level)')], db_column='tmtype', null=True),
        ),
        migrations.AlterField(
            model_name='toxicitymeasure',
            name='unit',
            field=models.ForeignKey(blank=True, db_column='unit_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.unit'),
        ),
        migrations.DeleteModel(
            name='servot',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.AddField(
            model_name='proteinreceptor',
            name='receptor',
            field=models.ForeignKey(db_column='receptor_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.receptor'),
        ),
        migrations.AddField(
            model_name='comprecep',
            name='receptor',
            field=models.ForeignKey(blank=True, db_column='receptor_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.receptor'),
        ),
        migrations.AddField(
            model_name='certso',
            name='so',
            field=models.ForeignKey(blank=True, db_column='so_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.servorg'),
        ),
        migrations.AddField(
            model_name='certpl',
            name='pl',
            field=models.ForeignKey(blank=True, db_column='pl_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.pricelist'),
        ),
        migrations.AddField(
            model_name='nanoparticle',
            name='npt',
            field=models.ForeignKey(blank=True, db_column='npt_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.nptype'),
        ),
    ]
