# Generated by Django 4.2.16 on 2026-04-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0044_toxicitymeasure_remove_extfactnpint_npi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='certification',
            fields=[
                ('cert_id', models.AutoField(primary_key=True, serialize=False)),
                ('certtype', models.IntegerField(blank=True, db_column='certtype', null=True)),
                ('certtitle', models.CharField(blank=True, db_column='certtitle', max_length=30, null=True)),
                ('certdesc', models.TextField(blank=True, db_column='certdesc', null=True)),
            ],
            options={
                'db_table': 'certification',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('prod_id', models.AutoField(db_column='prod_id', primary_key=True, serialize=False)),
                ('prodtitle', models.CharField(blank=True, db_column='prodtitle', max_length=255, null=True)),
                ('proddesc', models.TextField(blank=True, db_column='proddesc', null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='receptor',
            fields=[
                ('receptor_id', models.AutoField(db_column='receptor_id', primary_key=True, serialize=False)),
                ('receptorname', models.CharField(blank=True, db_column='receptorname', max_length=50, null=True)),
                ('receptordesc', models.TextField(blank=True, db_column='receptordesc', null=True)),
            ],
            options={
                'db_table': 'receptor',
            },
        ),
        migrations.CreateModel(
            name='strategicdirection',
            fields=[
                ('sd_id', models.AutoField(db_column='sd_id', primary_key=True, serialize=False)),
                ('sdtitle', models.CharField(blank=True, db_column='sdtitle', max_length=255, null=True)),
                ('sdddesc', models.TextField(blank=True, db_column='sddesc', null=True)),
            ],
            options={
                'db_table': 'strategicdirection',
            },
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='contdesc',
            field=models.TextField(blank=True, db_column='contdesc', null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='conttype',
            field=models.IntegerField(blank=True, choices=[(1, 'Telephone number'), (2, 'Cell-phone number'), (3, 'Email'), (4, 'Web-site URL'), (5, 'LinkedIn'), (6, 'WhataApp'), (7, 'Twitter'), (8, 'Instagram'), (9, 'Telegram')], db_column='ContType', null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='engagement',
            field=models.IntegerField(blank=True, choices=[(1, 'Domain Focus'), (2, 'Expertise'), (3, 'Strategic Direction'), (4, 'Capability'), (5, 'Education'), (6, 'Interested'), (7, 'Experienced'), (8, 'Talented'), (9, 'Occupation')], db_column='Engagement', null=True),
        ),
        migrations.AddField(
            model_name='nanoparticle',
            name='profiletype',
            field=models.IntegerField(blank=True, choices=[(1, 'Reference'), (2, 'Studied'), (3, 'Research Goal')], db_column='profiletype', null=True),
        ),
        migrations.AddField(
            model_name='stakeholderrole',
            name='prole',
            field=models.ForeignKey(blank=True, db_column='prole_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.stakeholderrole'),
        ),
        migrations.CreateModel(
            name='proteinreceptor',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('protein', models.ForeignKey(db_column='protein_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.protein')),
                ('receptor', models.ForeignKey(db_column='receptor_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.receptor')),
            ],
            options={
                'db_table': 'proteinreceptor',
            },
        ),
        migrations.CreateModel(
            name='prodorg',
            fields=[
                ('po_id', models.AutoField(db_column='po_id', primary_key=True, serialize=False)),
                ('tat', models.DecimalField(blank=True, db_column='tat', decimal_places=0, max_digits=4, null=True)),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.organization')),
                ('prod_id', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.product')),
            ],
            options={
                'db_table': 'prodorg',
            },
        ),
        migrations.CreateModel(
            name='orgsd',
            fields=[
                ('osd_id', models.AutoField(primary_key=True, serialize=False)),
                ('osdtitle', models.CharField(blank=True, db_column='osdtitle', max_length=255, null=True)),
                ('osdddesc', models.TextField(blank=True, db_column='osddesc', null=True)),
                ('priority', models.DecimalField(blank=True, db_column='priority', decimal_places=2, max_digits=5, null=True)),
                ('organization', models.ForeignKey(db_column='Organization_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.organization')),
                ('sd', models.ForeignKey(db_column='sd_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.strategicdirection')),
            ],
            options={
                'db_table': 'orgsd',
            },
        ),
        migrations.CreateModel(
            name='nptype',
            fields=[
                ('npt_id', models.AutoField(db_column='npt_id', primary_key=True, serialize=False)),
                ('npttitle', models.CharField(blank=True, db_column='npttitle', max_length=30, null=True)),
                ('nptdesc', models.TextField(blank=True, db_column='nptdesc', null=True)),
                ('pnpt', models.ForeignKey(blank=True, db_column='pnpt_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.nptype')),
            ],
            options={
                'db_table': 'nptype',
            },
        ),
        migrations.CreateModel(
            name='inttissue',
            fields=[
                ('it_id', models.AutoField(db_column='it_id', primary_key=True, serialize=False)),
                ('intervention', models.ForeignKey(blank=True, db_column='intervention_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='longevity.intervention')),
                ('tissue', models.ForeignKey(blank=True, db_column='tissue_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='longevity.tissue')),
            ],
            options={
                'db_table': 'inttissue',
            },
        ),
        migrations.CreateModel(
            name='intcelltype',
            fields=[
                ('ict_id', models.AutoField(db_column='ict_id', primary_key=True, serialize=False)),
                ('ct', models.ForeignKey(blank=True, db_column='ct_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='longevity.celltype')),
                ('intervention', models.ForeignKey(blank=True, db_column='intervention_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='longevity.intervention')),
            ],
            options={
                'db_table': 'intcelltype',
            },
        ),
        migrations.CreateModel(
            name='comprecep',
            fields=[
                ('cr_id', models.AutoField(db_column='cr_id', primary_key=True, serialize=False)),
                ('comp', models.ForeignKey(blank=True, db_column='comp_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.component')),
                ('receptor', models.ForeignKey(blank=True, db_column='receptor_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.receptor')),
            ],
            options={
                'db_table': 'comprecep',
            },
        ),
        migrations.CreateModel(
            name='certpo',
            fields=[
                ('cpo_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, db_column='score', null=True)),
                ('link', models.CharField(blank=True, db_column='link', max_length=255, null=True)),
                ('cert', models.ForeignKey(blank=True, db_column='cert_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.certification')),
                ('po', models.ForeignKey(blank=True, db_column='po_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.prodorg')),
            ],
            options={
                'db_table': 'certpo',
            },
        ),
        migrations.CreateModel(
            name='certpl',
            fields=[
                ('cpl_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, db_column='score', null=True)),
                ('link', models.CharField(blank=True, db_column='link', max_length=255, null=True)),
                ('cert', models.ForeignKey(blank=True, db_column='cert_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.certification')),
                ('pl', models.ForeignKey(blank=True, db_column='pl_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.pricelist')),
            ],
            options={
                'db_table': 'certpl',
            },
        ),
        migrations.CreateModel(
            name='certorg',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, db_column='score', null=True)),
                ('link', models.CharField(blank=True, db_column='link', max_length=255, null=True)),
                ('cert', models.ForeignKey(blank=True, db_column='cert_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.certification')),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.organization')),
            ],
            options={
                'db_table': 'certorg',
            },
        ),
        migrations.AddField(
            model_name='nanoparticle',
            name='npt',
            field=models.ForeignKey(blank=True, db_column='npt_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.nptype'),
        ),
    ]
