# Generated by Django 4.2.16 on 2026-04-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0045_certification_product_receptor_strategicdirection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeholderOrg',
            fields=[
                ('so_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.ForeignKey(db_column='Organization_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.organization')),
                ('project', models.ForeignKey(db_column='Project_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.project')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.stakeholderrole')),
            ],
            options={
                'db_table': 'stakeholderorg',
            },
        ),
    ]
