# Generated by Django 4.2.1 on 2025-07-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0045_certification_certorg_certpl_certso_comprecep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='contdesc',
            field=models.TextField(blank=True, db_column='contdesc', null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='conttype',
            field=models.IntegerField(blank=True, choices=[(1, 'Telephone number'), (2, 'Cell-phone number'), (3, 'Email'), (4, 'Web-site URL'), (5, 'LinkedIn'), (6, 'WA'), (7, 'Twitter'), (8, 'Instagram'), (9, 'Telegram')], db_column='ContType', null=True),
        ),
    ]
