# Generated by Django 4.2.16 on 2026-04-19 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0046_stakeholderorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawbacktype',
            name='parentdbt',
            field=models.ForeignKey(blank=True, db_column='parentdbt_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longevity.drawbacktype'),
        ),
    ]
