# Generated by Django 4.2.16 on 2026-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0047_drawbacktype_parentdbt'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholderrole',
            name='eicmp',
            field=models.IntegerField(blank=True, db_column='eicmp', null=True),
        ),
    ]
