# Generated by Django 4.2.16 on 2026-06-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longevity', '0048_stakeholderrole_eicmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='networkmodel',
            field=models.IntegerField(blank=True, db_column='networkmodel', null=True),
        ),
    ]
